config/routes.rb
Rails.application.routes.draw do
  resources :posts
  
  get 'home'      => 'navigate#home'

  get 'about'     => 'navigate#about'

  get 'contact'   => 'navigate#contact'

  get 'projects'  => 'navigate#projects'

  root 'navigate#home'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/navigate_controller.rb
class NavigateController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def projects
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_filter :authenticate, :except => [ :index, :show ]

	def new
	end

	def index
		@posts = Post.all
	end

	def create
		@post = Post.new(post_params)

		@post.save
		redirect_to @post
	end

	def show
		@post = Post.find(params[:id])
	end

		private
			def post_params
				params.require(:post).permit(:title, :content)
			end

			def authenticate
		    	authenticate_or_request_with_http_basic do |name, password|
		      	name == "hungvt4" && password == "ruby"
		    	end
		  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/navigate_helper.rb
module NavigateHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<head>
</head>
<body>
<footer class="footer fill-background">
  <small>
:::
  </small>
  <nav>
    <ul>
      <li><%= link_to "CV",   'CV.pdf', :target => "_blank" %>
	  </li>
      <li><%= link_to "Resume", 'Resume.pdf', :target => "_blank" %>
      </li>
    </ul>
  </nav>
</footer>
<body>

app/views/layouts/_header.html.erb
<head>
<meta charset="UTF-8">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
<style type="text/css">
  .bs-example{
      margin: 0px;
    }
</style>
</head>
<body>
<div class="bs-example">
    <nav id="myNavbar" class="navbar navbar-inverse" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="container-fullwidth">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu-items">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "H", root_path, id: "logo" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="menu-items">
                <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to "About",   'about' %></li>
                    <li><%= link_to "Projects",   'projects' %></li>
                    <li><%= link_to "Blog", 'posts' %></li>
                    <li><%= link_to "Contact", 'contact' %></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div>
    </nav>
</div>
</body>
</html>                                   

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hung V Tran</title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
      <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400' rel='stylesheet' type='text/css'>
</head>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  <div id = "wrapper">
    <div id= "header">
      <%= render 'layouts/header' %>
    </div><!--
    header-to-content
    -->
    <div id= "content">
      <%= yield %>
    </div>
    <div class="container" id = "footer">
      <%= render 'layouts/footer' %>
    </div>
  </div>  
  </body>
</html>

app/views/navigate/about.html.erb
<div class="headerbox">
<h1>About</h1>
<div>
<h2>I'm currently a 4th year Pharm. D. student interning at the FDA (Food and Drug Administration), and will be graduating in May 2015. I think of myself as a renaissance man, and am always looking forward to learn new things. Below is a list of my competencies in various areas, but expect them to grow larger soon!
</h2>
</div> 

<section id="about-lists">
	<h1>
	My current skill-set includes:
	</h1>
	<br>
<article class="col-md-4">
	<h1>
	Computer Science:
	</h1>
	<h2>
	<ul>
		<li>Ruby (Ranked Top 5% on codeeval.com),</li>
		<li>Ruby on Rails Framework (Framework used to build this website),</li>
		<li>Bootstrap (HTML/CSS/JS Framework used to format this website),</li>
		<li>HTML,</li>
		<li>CSS,</li>
		<li>SQL</li>
	</ul>
	</h2>
</article>

<article class="col-md-4">
	<h1>Pharmacy:</h1>
	<h2>
	<ul>
		<li>Clinical Skills: 2 years work experience as Intern Pharmacist at Providence Tarzana Medical Center,
		</li>
		<li>Western University Oncology Research Fellowship: Authored research grant which funded fellowship. Completed fellowship of non-clinical pharmacokinetic study of novel vehicle 
		for delivering daunorubicin in pancreatic cancer,
		</li>
	</ul>
	</h2>
</article>

<article class="col-md-4">
	<h1>Pharmaceutical Industry:</h1>
	<h2>
	<ul>
		<li>Regulatory Experience: Intern for 6 months at FDA in ONDQA (Office of New Drug Quality Assessment) and SEALD (Study Endpoints and Labeling Division),
		</li>
		<li>Medical Information/Affairs: Intern for 6 weeks at Gilead Sciences and drafted cobicistat monograph. Familiar with IRMS (Information Request Management System) software,
		</li>
		<li>Drug Safety: Received Drug Safety Associate Certification from Q-tech Solutions
		</li>
	</ul>
	</h2>
</article>

<div>
<h2>*For a more details of any area, please refer to my Resume or CV.
</h2>
<div>

</section>
</div>

app/views/navigate/contact.html.erb
<div class="headerbox">
		<h1>Contact</h1>
	<div>
		<h2>Email: hungvt4@gmail.com
		</h2>
		<h2>Phone: (408) 230-7154
		</h2>
	</div>
</div>

app/views/navigate/home.html.erb
<div class="headerbox">
	  <h1>Welcome!</h1>
	  <div>
	  <h2>Hi, my name is Hung V Tran, and I'm a Rails Developer.</h2>
	</div>  
</div>

app/views/navigate/projects.html.erb
<div class="headerbox">
		<h1>Projects</h1>
	<div>
		<h2>Pending...</h2>
	</div>
</div>

app/views/posts/index.html.erb
<div class="headerbox">
<h1>Blog</h1>
 
 
  <% @posts.each do |post| %>
    <tr>
      <h3 id="post_title">
      <td><%= post.title %></td>
      </h3>
      <h2>
      Posted <%= post.created_at.strftime('%m/%d/%Y') %>
      <br>
      <td><%= post.content %></td>
      </h2>
    </tr>
  <% end %>

<h2>
<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<div class="headerbox">
<h1>New Post</h1>

<%= form_for :post, url: posts_path do |f| %>
<h2>
	<%= f.label :title %><br>
	<%= f.text_field :title %>
</h2>

<h2>
	<%= f.label :content %><br>
	<%= f.text_area :content %>
</h2>

<h2>
	<%= f.submit %>
</h2>
<% end %>
</div>

app/views/posts/show.html.erb
<div class="headerbox">
<h1>

  <%= @post.title %>

</h1>
 
<h2>
  <%= @post.content %>
</h2>
</div>